runtime: go
env: flex

# default cache expiration is 10 min
default_expiration: "5m"

handlers:
- url: /
  static_files: index.html
  expiration: "1s"
  upload: index.html
  secure: always
  redirect_http_response_code: 301
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: _go_app
  expiration: "1s"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
