runtime: python27
api_version: 1
threadsafe: true

# default cache expiration is 10 min
default_expiration: "5m"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  redirect_http_response_code: 301
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
