runtime: go
env: flex
service: backend

# default cache expiration is 10 min
default_expiration: "5m"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
